### ISSUE TITLE
Environment TODO

### ISSUE THREAD

**Issue by nigelnnk** [kenghweeng/Code_NoClue#2]
# General
- [ ] Code cleanup. I did this in a hacky cpp way and some representations can be made more explicit like for acuities and resources and events.
- [ ] Check valid action can be spun off into another method
- [ ] Check for bugs for single resource multiple acuities 
- [ ] Check for bugs for multiple resource single acuities 
- [ ] Check for bugs for multiple resource multiple acuities 

# State
- State representation is not good enough. It needs to show which resources are free and the waiting time of patients. Currently it's only a proportional representation of acuities per resource
- [ ] Check for other representational issues

# Action
- [ ] Check if action representation has enough variety to solve problem
- [ ] Remove asserts for invalid action and just penalise agent

# Reward
- [ ] Keep track of cumulative reward
- [ ] Keep track of total waiting time

# Other
- [ ] Get static representation of whole problem (ie. Patient arrival time, treatment order, treatment times) to use for offline analysis
